### ISSUE TITLE
What's the led on the keyboard used for ?

### ISSUE THREAD

**Issue by YCF** [reversebias/mitosis-hardware#3]
The Caps and Layers led is on the receiver,what about the keyboard one(two...)?
Am I missing some lines of the code ?

**Comment by TyberiusPrime** [comment]
reversebias mentioned on reddit that he had those on there so that he could do the time-honored 'blinky' test during development. 
I'd imagine they'd have a drastic effect on the battery drain.

**Comment by reversebias** [comment]
TyberiusPrime is right, it was only used for initial sanity checks during toolchain setup. You can't even see it once the keyboard is fully assembled. :)
