### ISSUE TITLE
What's the P-D3/P29 connection for?

### ISSUE THREAD

**Issue by datagrok** [reversebias/mitosis-hardware#7]
It looks from the receiver schematic like Pro Micro pin 3 (PD0) is connected to P29 on the NRF51 module (labeled P-D3) but I don't see anywhere that that connection is being used. What is it for?

**Comment by datagrok** [comment]
Oh derp, it's connected to the pairing switch. Nevermind! 😄

**Comment by reversebias** [comment]
Unimplemented, but yeah.
